license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://github.com/yigit-guven/Chymistry"
issueTrackerURL="https://github.com/yigit-guven/Chymistry/issues"
updateJSONURL="https://raw.githubusercontent.com/yigit-guven/Chymistry/26.2-neoforge/update.json"
authors="Yiğit Güven"
credits="Thanks to my friend Rwkersa for the idea and evolution of the idea, and to Curseforge ModJam 2026 for being the starting point!"
description='''
A comprehensive Chymistry mod for Minecraft.
'''

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
